### ISSUE TITLE
Cargo bay does not shield stuff inside

### ISSUE THREAD

**Issue by PortableGoogle** [SuicidalInsanity/Mk3Expansion#8]
Parts inside cargobay heat up and can explode as well as parts that shouldn't work with bays closed like the dmagic atmosphere analysis thing work with the doors closed. This is the J size cargo bay, not sure if others have the problem as well.

**Comment by SuicidalInsanity** [comment]
M3X doesn't add J size parts - that's an OPT part.

**Comment by PortableGoogle** [comment]
Sorry about that, wasn't paying attention and put this in the wrong place.
